title: Pratyush Patra
description: M.Stat student at ISI Kolkata | Statistics
theme: jekyll-theme-minimal-mistakes
google_analytics: G-75E04PH759

#Navigation bar settings
header_pages:
  - index.md
  - academics.md
  - readings.md
  - personal.md
