title: Pratyush Patra
description: M.Stat student at ISI Kolkata | Statistics
# theme: minimal-mistakes-jekyll  # Comment this out
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
google_analytics: G-75E04PH759

#Navigation bar settings
header_pages:
  - index.md
  - academics.md
  - readings.md
  - personal.md
